### ISSUE TITLE
setPlayerSize() set class to empty string

### ISSUE THREAD

**Issue by isitrita** [sashaegorov/foundation-player#1]
https://github.com/qatsi/foundation-player.js/blob/feature/change-size/src/foundation-player.coffee#L214:L217

**Comment by sashaegorov** [comment]
@isitrita I'm going to ignore incorrect value if user specified something which differs from `normal` or `small`.

**Comment by isitrita** [comment]
@qatsi 
Do you agree, that for cases like `setPlayerSize()` or `setPlayerSize('something underfined')` some default size of player should be applied?

**Comment by isitrita** [comment]
Current implementation has an error, check case
1. setPlayerSize('small')
2. setPlayerSize('small')

**Comment by sashaegorov** [comment]
Got it. I'll just ignore everything except `normal` or `small`.

**Comment by isitrita** [comment]
Ok, now it works as expected. Close issue.
